sudo: required

language: python
python:
  - "3.6"

if: branch IN (master)

before_install:
  - openssl aes-256-cbc -K $encrypted_07459ba4a5ab_key -iv $encrypted_07459ba4a5ab_iv -in rocketleaguekey.pem.enc -out rocketleaguekey.pem -d

script:
  - echo "ZOOOOOB"
  - ls
  - pwd
